### PR TITLE
Add support for the `disabled` attribute on radio inputs.

### PR DESCRIPTION
**Pull request by neaket360pi**
Tested in Chrome and FireFox

https://github.com/Blooie/ember-radio-buttons/issues/5

### CODE REVIEW

**Comment by slightlytyler** [comment]
Would love to see this merged and NPM updated!

**Comment by mansona** [comment]
cool, looks simple enough! **merging**

**Comment by mansona** [comment]
that's been published too :+1:

**Comment by neaket360pi** [comment]
Thank you. :smile:

**Comment by slightlytyler** [comment]
@neaket360pi @mansona  thanks!

**Pull request merged**
