### PR TITLE
Add option to trigger 'action' on change

### PR DESCRIPTION
**Pull request by anilmaurya**

### CODE REVIEW

**Comment by mszoernyi** [comment]
I would suggest to use the components `action` attribute.
http://emberjs.com/guides/components/sending-actions-from-components-to-your-application/#toc_sending-a-primary-action

**Comment by anilmaurya** [comment]
@mszoernyi May be in future some other action (like 'changed') need to be listen therefore limiting to only one action is not a good idea.

**Comment by anilmaurya** [comment]
@mszoernyi thanks for your comment on #10 , 'actionToBeCalled' make more sense. Updated readme.

**Comment by mansona** [comment]
I don't understand the need for and action to be called from inside the radio button, why can't you just have a computed property or an observer watching the value that the radio button is bound to?

**Comment by mansona** [comment]
This has already been discussed here: https://github.com/Blooie/ember-radio-buttons/issues/4

**Comment by anilmaurya** [comment]
@mansona I have div like this

    <div class="aspect-ratio">
        Aspect Ratio:
        {{radio-button name="aspectRatio[]" value='1' changed="changeAspectRatio" checked='1'}} 1:1
        {{radio-button name="aspectRatio[]" value='1.33' changed="changeAspectRatio"}} 4:3
        {{radio-button name="aspectRatio[]" value='1.77' changed="changeAspectRatio"}} 16:9
      </div>

It generates 3 radio buttons for selecting Aspect Ratio.

I think it make sense to directly invoke changeAspectRatio from radio-button instead binding an observer on radio-button value.

**Comment by mansona** [comment]
@anilmaurya you can quite easily bind an observer and emit an action from the controller if you really need it to be an action, otherwise you can always override the default implementation with your own component very similar to what you see here: https://github.com/Blooie/ember-radio-buttons/blob/master/app/components/radio-button.js

Instead of just re-exporting in your app you would extend the ember-radio-button component and have something like a `{{action-radio-button}}` component that gives you the functionality that you need. Let me know if you need any more guidance on this

**Comment by anilmaurya** [comment]
I extended ember-radio-button for my application and I thought  its useful for others. Anyway, thanks for writing this plugin .

**Pull request closed without merging**
